# EDIT THIS FILE ACCORDING TO YOUR EXPERIMENTAL SETUP
# FLEXBAR
flexbar_max_uncalled: 20
flexbar_min_length: 20
flexbar_min_qual: 20
# PARAMETERS
ref_annotation_file: references/PROKKA_07132018_Edited.gff
ref_annotation_feature_type: CDS
ref_annotation_gene_type: ID
ref_fasta_file: references/9409_1#5.fa
ref_index_name: REF_Transduziert
# PATHS
bowtie2_path: ./libraries/bowtie2/bowtie2
bowtie2_build_path: ./libraries/bowtie2/bowtie2-build
flexbar_path: ./libraries/flexbar/flexbar
# SAMPLES
metadata_file: Metadata.tsv