# EDIT THIS FILE ACCORDING TO YOUR EXPERIMENTAL SETUP
# PLEASE REFER TO THE WIKI FOR MORE INFORMATION ABOUT INDIVIDUAL PARAMETERS
# https://github.com/SiWolf/SCORE/wiki
# --------------
# BASIC SETTINGS
# --------------
analysis_name: Houser
metadata_file: raw/Metadata_Houser_et_al.tsv
param_threshold: 0.05
param_total_genes: 5000
ref_annotation_file: references/GCF_000005845.2_ASM584v2_genomic.gff
ref_annotation_feature: gene
ref_annotation_identifier: locus_tag
ref_genome: references/GCF_000005845.2_ASM584v2_genomic.fna
genescf_organism: prokaryota
genescf_go_db: ecocyc
genescf_kegg_db: eco
# -----------------
# ADVANCED SETTINGS
# -----------------
# FLEXBAR
flexbar_max_uncalled: 20
flexbar_min_length: 20
flexbar_min_qual: 20
# MISCELLANEOUS
kallisto_bootstrap: 100
kallisto_length_deviation: 5
kallisto_read_length: 100
genescf_path: ./libraries/geneSCF/geneSCF
ncbi_genetic_code_table: 11
noiseq_biological_replicates: TRUE
# REFERENCES
ref_go_obo: references/go.obo
ref_index: REF_INDEX
ref_tigrfam_library: references/tigrfam/TIGRFAMs_15.0_HMM.LIB
ref_tigrfam_links: references/tigrfam/TIGRFAMS_ROLE_LINK
ref_tigrfam_roles: references/tigrfam/TIGR_ROLE_NAMES
ref_transcriptome: references/REF.ffn
# SCORE
score_benchmarking: FALSE
score_generate_transcriptome: TRUE
score_low_expression_count: 10
score_merge_plots: TRUE
score_strict_mode: TRUE
score_threshold: 0.5
# WEIGHTS - DEFAULT - MAJORITY VOTE
# weight_bayseq: 1.0
# weight_deseq2: 1.0
# weight_edger: 1.0
# weight_limma: 1.0
# weight_noiseq: 1.0
# weight_sleuth: 1.0
# WEIGHTS - DEFAULT - STABLE
weight_bayseq: 0.5
weight_deseq2: 1.5
weight_edger: 0.5
weight_limma: 1.5
weight_noiseq: 0.5
weight_sleuth: 1.5
# WEIGHTS - DEFAULT - EXPERIMENTAL
# weight_bayseq: 0.5
# weight_deseq2: 1.0
# weight_edger: 0.5
# weight_limma: 1.0
# weight_noiseq: 0.5
# weight_sleuth: 2.5
