# EDIT THIS FILE ACCORDING TO YOUR EXPERIMENTAL SETUP
# DEG PREDICTION CUTOFFS
general_threshold: 0.05
enable_strict_mode: TRUE
low_expression_count: 5
score_threshold: 0.5
# FLEXBAR SETTINGS
flexbar_max_uncalled: 20
flexbar_min_length: 20
flexbar_min_qual: 20
# GENESCF SETTINGS
genescf_go_db: ecocyc
genescf_kegg_db: ecg
genescf_total_genes_species: 5000
# MISCELLANEOUS
analysis_name: T1
merge_plots_into_pdf: FALSE
noiseq_assume_biological_replicates: TRUE
# PARAMETERS
ref_annotation_file: references/human_untransduced/PROKKA_07132018.gff
ref_annotation_feature_type: CDS
ref_annotation_gene_type: locus_tag
ref_fasta_file: references/human_untransduced/7738_8#57.fa
ref_fasta_transcriptome: references/human_untransduced/PROKKA_07132018.ffn
ref_index_name: REF_untransduced
# PATHS
flexbar_path: ./libraries/flexbar/flexbar
geneSCF_path: ./libraries/geneSCF/geneSCF
# SAMPLES
metadata_file: Metadata_C1.tsv
# WEIGHTS FOR CONSENSUS PREDICTION
# DEFAULT - MAJORITY VOTE
weight_bayseq: 1.0
weight_deseq2: 1.0
weight_edger: 1.0
weight_limma: 1.0
weight_noiseq: 1.0
weight_sleuth: 1.0
# DEFAULT - STABLE
# weight_bayseq: 0.5
# weight_deseq2: 1.5
# weight_edger: 1.0
# weight_limma: 1.0
# weight_noiseq: 1.5
# weight_sleuth: 0.5
# DEFAULT - EXPERIMENTAL
# weight_bayseq: 0.5
# weight_deseq2: 1.0
# weight_edger: 0.75
# weight_limma: 0.75
# weight_noiseq: 2.5
# weight_sleuth: 0.5
# BENCHMARKING
benchmarking: FALSE