# EDIT THIS FILE ACCORDING TO YOUR EXPERIMENTAL SETUP
# DEG TOOLS
bayseq_threshold: 0.03
general_threshold: 0.05
# TO-DO: Implement these weights into the Snakefile and R scripts
weight_bayseq: 1.0
weight_deseq2: 1.0
weight_edger: 1.0
weight_limma: 1.0
weight_noiseq: 1.0
# FLEXBAR
flexbar_max_uncalled: 20
flexbar_min_length: 20
flexbar_min_qual: 20
# PARAMETERS
ref_annotation_file: references/PROKKA_07132018_Edited.gff
ref_annotation_feature_type: CDS
ref_annotation_gene_type: ID
ref_fasta_file: references/9409_1#5.fa
ref_index_name: REF_Transduziert
# PATHS
flexbar_path: ./libraries/flexbar/flexbar
# SAMPLES
metadata_file: Metadata.tsv