# Visualize DEG prediction accuracy

setwd("../../degs/")

# Data preprocessing
data_1 <- read.csv(file = "1/deg_summary.csv", header = TRUE, sep = ",")
data_2 <- read.csv(file = "2/deg_summary.csv", header = TRUE, sep = ",")
data_3 <- read.csv(file = "3/deg_summary.csv", header = TRUE, sep = ",")
data_4 <- read.csv(file = "4/deg_summary.csv", header = TRUE, sep = ",")
data_5 <- read.csv(file = "5/deg_summary.csv", header = TRUE, sep = ",")
data_6 <- read.csv(file = "6/deg_summary.csv", header = TRUE, sep = ",")

data_frame_accuracy = data.frame(data_1$X, data_1$ACC, data_2$ACC, data_3$ACC, data_4$ACC, data_5$ACC, data_6$ACC)
data_frame_degs = data.frame(data_1$X, data_1$DEGS, data_2$DEGS, data_3$DEGS, data_4$DEGS, data_5$DEGS, data_6$DEGS)
data_frame_fns = data.frame(data_1$X, data_1$FN, data_2$FN, data_3$FN, data_4$FN, data_5$FN, data_6$FN)
data_frame_fps = data.frame(data_1$X, data_1$FP, data_2$FP, data_3$FP, data_4$FP, data_5$FP, data_6$FP)
data_frame_tns = data.frame(data_1$X, data_1$TN, data_2$TN, data_3$TN, data_4$TN, data_5$TN, data_6$TN)
data_frame_tps = data.frame(data_1$X, data_1$TP, data_2$TP, data_3$TP, data_4$TP, data_5$TP, data_6$TP)
data_frame_tpr = data.frame(data_1$X, data_1$TPR, data_2$TPR, data_3$TPR, data_4$TPR, data_5$TPR, data_6$TPR)
data_frame_tnr = data.frame(data_1$X, data_1$TNR, data_2$TNR, data_3$TNR, data_4$TNR, data_5$TNR, data_6$TNR)

tools <- c("baySeq", "DESeq2", "edgeR", "limma", "NOISeq", "sleuth", "SCORE")

# Accuracy
png(filename = "benchmarking_diagram_acc.png", width = 20, height = 20, units = "cm", res = 600)
plot(data_1$ACC, type = "o", lty = 1, pch = 15, col = "blue", ylim = c(0.97, 1), axes = FALSE, xlab = "Tools", ylab = "Amount of identified DEGs", lwd = 2.5)
axis(1, 1:7, lab = tools)
axis(2)
lines(data_2$ACC, type = "o", lty = 1, pch = 16, col = "red", lwd = 2.5)
lines(data_3$ACC, type = "o", lty = 1, pch = 17, col = "green", lwd = 2.5)
lines(data_4$ACC, type = "o", lty = 1, pch = 18, col = "orange", lwd = 2.5)
lines(data_5$ACC, type = "o", lty = 1, pch = 18, col = "grey", lwd = 2.5)
lines(data_6$ACC, type = "o", lty = 1, pch = 18, col = "black", lwd = 2.5)
box()
legend(1, 0.985, c("1", "2", "3", "4", "5", "6"), cex = 1.1, col = c("blue", "red", "green", "orange", "grey", "black"), pch = 15:18, lty = 1)
dev.off()

# DEGs
png(filename = "benchmarking_diagram_degs.png", width = 20, height = 20, units = "cm", res = 600)
plot(data_1$DEGS, type = "o", lty = 1, pch = 15, col = "blue", ylim = c(50, 600), axes = FALSE, xlab = "Tools", ylab = "Amount of identified DEGs", lwd = 2.5)
axis(1, 1:7, lab = tools)
axis(2)
lines(data_2$DEGS, type = "o", lty = 1, pch = 16, col = "red", lwd = 2.5)
lines(data_3$DEGS, type = "o", lty = 1, pch = 17, col = "green", lwd = 2.5)
lines(data_4$DEGS, type = "o", lty = 1, pch = 18, col = "orange", lwd = 2.5)
lines(data_5$DEGS, type = "o", lty = 1, pch = 18, col = "grey", lwd = 2.5)
lines(data_6$DEGS, type = "o", lty = 1, pch = 18, col = "black", lwd = 2.5)
box()
legend(1, 520, c("1", "2", "3", "4", "5", "6"), cex = 1.1, col = c("blue", "red", "green", "orange", "grey", "black"), pch = 15:18, lty = 1)
dev.off()

# FN
png(filename = "benchmarking_diagram_fns.png", width = 20, height = 20, units = "cm", res = 600)
plot(data_1$FN, type = "o", lty = 1, pch = 15, col = "blue", ylim = c(0, 25), axes = FALSE, xlab = "Tools", ylab = "Amount of identified DEGs", lwd = 2.5)
axis(1, 1:7, lab = tools)
axis(2)
lines(data_2$FN, type = "o", lty = 1, pch = 16, col = "red", lwd = 2.5)
lines(data_3$FN, type = "o", lty = 1, pch = 17, col = "green", lwd = 2.5)
lines(data_4$FN, type = "o", lty = 1, pch = 18, col = "orange", lwd = 2.5)
lines(data_5$FN, type = "o", lty = 1, pch = 18, col = "grey", lwd = 2.5)
lines(data_6$FN, type = "o", lty = 1, pch = 18, col = "black", lwd = 2.5)
box()
legend(1, 25, c("1", "2", "3", "4", "5", "6"), cex = 1.1, col = c("blue", "red", "green", "orange", "grey", "black"), pch = 15:18, lty = 1)
dev.off()

# FP
png(filename = "benchmarking_diagram_fps.png", width = 20, height = 20, units = "cm", res = 600)
plot(data_1$FP, type = "o", lty = 1, pch = 15, col = "blue", ylim = c(0, 125), axes = FALSE, xlab = "Tools", ylab = "Amount of identified DEGs", lwd = 2.5)
axis(1, 1:7, lab = tools)
axis(2)
lines(data_2$FP, type = "o", lty = 1, pch = 16, col = "red", lwd = 2.5)
lines(data_3$FP, type = "o", lty = 1, pch = 17, col = "green", lwd = 2.5)
lines(data_4$FP, type = "o", lty = 1, pch = 18, col = "orange", lwd = 2.5)
lines(data_5$FP, type = "o", lty = 1, pch = 18, col = "grey", lwd = 2.5)
lines(data_6$FP, type = "o", lty = 1, pch = 18, col = "black", lwd = 2.5)
box()
legend(1.2, 120, c("1", "2", "3", "4", "5", "6"), cex = 1.1, col = c("blue", "red", "green", "orange", "grey", "black"), pch = 15:18, lty = 1)
dev.off()

# TN
png(filename = "benchmarking_diagram_tns.png", width = 20, height = 20, units = "cm", res = 600)
plot(data_1$TN, type = "o", lty = 1, pch = 15, col = "blue", ylim = c(4100, 4700), axes = FALSE, xlab = "Tools", ylab = "Amount of identified DEGs", lwd = 2.5)
axis(1, 1:7, lab = tools)
axis(2)
lines(data_2$TN, type = "o", lty = 1, pch = 16, col = "red", lwd = 2.5)
lines(data_3$TN, type = "o", lty = 1, pch = 17, col = "green", lwd = 2.5)
lines(data_4$TN, type = "o", lty = 1, pch = 18, col = "orange", lwd = 2.5)
lines(data_5$TN, type = "o", lty = 1, pch = 18, col = "grey", lwd = 2.5)
lines(data_6$TN, type = "o", lty = 1, pch = 18, col = "black", lwd = 2.5)
box()
legend(1, 4500, c("1", "2", "3", "4", "5", "6"), cex = 1.1, col = c("blue", "red", "green", "orange", "grey", "black"), pch = 15:18, lty = 1)
dev.off()

# TP
png(filename = "benchmarking_diagram_tps.png", width = 20, height = 20, units = "cm", res = 600)
plot(data_1$TP, type = "o", lty = 1, pch = 15, col = "blue", ylim = c(50, 550), axes = FALSE, xlab = "Tools", ylab = "Amount of identified DEGs", lwd = 2.5)
axis(1, 1:7, lab = tools)
axis(2)
lines(data_2$TP, type = "o", lty = 1, pch = 16, col = "red", lwd = 2.5)
lines(data_3$TP, type = "o", lty = 1, pch = 17, col = "green", lwd = 2.5)
lines(data_4$TP, type = "o", lty = 1, pch = 18, col = "orange", lwd = 2.5)
lines(data_5$TP, type = "o", lty = 1, pch = 18, col = "grey", lwd = 2.5)
lines(data_6$TP, type = "o", lty = 1, pch = 18, col = "black", lwd = 2.5)
box()
legend(1, 480, c("1", "2", "3", "4", "5", "6"), cex = 1.1, col = c("blue", "red", "green", "orange", "grey", "black"), pch = 15:18, lty = 1)
dev.off()

# TNR
png(filename = "benchmarking_diagram_tnr.png", width = 20, height = 20, units = "cm", res = 600)
plot(data_1$TNR, type = "o", lty = 1, pch = 15, col = "blue", ylim = c(0.97, 1), axes = FALSE, xlab = "Tools", ylab = "Amount of identified DEGs", lwd = 2.5)
axis(1, 1:7, lab = tools)
axis(2)
lines(data_2$TNR, type = "o", lty = 1, pch = 16, col = "red", lwd = 2.5)
lines(data_3$TNR, type = "o", lty = 1, pch = 17, col = "green", lwd = 2.5)
lines(data_4$TNR, type = "o", lty = 1, pch = 18, col = "orange", lwd = 2.5)
lines(data_5$TNR, type = "o", lty = 1, pch = 18, col = "grey", lwd = 2.5)
lines(data_6$TNR, type = "o", lty = 1, pch = 18, col = "black", lwd = 2.5)
box()
legend(1.2, 0.985, c("1", "2", "3", "4", "5", "6"), cex = 1.1, col = c("blue", "red", "green", "orange", "grey", "black"), pch = 15:18, lty = 1)
dev.off()

# TPR
png(filename = "benchmarking_diagram_tpr.png", width = 20, height = 20, units = "cm", res = 600)
plot(data_1$TPR, type = "o", lty = 1, pch = 15, col = "blue", ylim = c(0.94, 1), axes = FALSE, xlab = "Tools", ylab = "Amount of identified DEGs", lwd = 2.5)
axis(1, 1:7, lab = tools)
axis(2)
lines(data_2$TPR, type = "o", lty = 1, pch = 16, col = "red", lwd = 2.5)
lines(data_3$TPR, type = "o", lty = 1, pch = 17, col = "green", lwd = 2.5)
lines(data_4$TPR, type = "o", lty = 1, pch = 18, col = "orange", lwd = 2.5)
lines(data_5$TPR, type = "o", lty = 1, pch = 18, col = "grey", lwd = 2.5)
lines(data_6$TPR, type = "o", lty = 1, pch = 18, col = "black", lwd = 2.5)
box()
legend(1, 0.99, c("1", "2", "3", "4", "5", "6"), cex = 1.1, col = c("blue", "red", "green", "orange", "grey", "black"), pch = 15:18, lty = 1)
dev.off()